"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Se leen del archivo .env, que nunca se sube al repositorio.
SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG', default=False, cast=bool)

# Csv() convierte el texto "a,b,c" en la lista ['a', 'b', 'c']
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'productos',
    'pedidos',
    'usuarios',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='db'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators>
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# La tienda está en Venezuela: idioma español de Venezuela
# y hora de Caracas (UTC-4).
LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde collectstatic reune todos los archivos estaticos
# (admin de Django, DRF...) para que los sirva el servidor en produccion.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================
# Seguridad: CORS y CSRF
# ============================================================
# Antes se permitian TODOS los origenes. Ahora solo los del .env.
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

# Dominios de confianza para los formularios (admin de Django).
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())

# En produccion (DEBUG=False) las cookies solo viajan por HTTPS.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Nginx recibe el HTTPS y pasa la peticion a Django por HTTP:
    # esta cabecera le dice a Django que el origen era seguro.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================================
# HTTPS
# ============================================================
# Se leen del .env en vez de fijarlas aqui: en local no hay certificado,
# y activarlas dejaria el entorno de desarrollo inservible.
#
# SECURE_SSL_REDIRECT: Django redirige a HTTPS cualquier peticion que
# llegue por HTTP. Nginx ya lo hace, pero esto cubre el caso de que
# alguien alcance a Django por otra via.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# HSTS: cabecera que le dice al navegador "para este dominio, usa HTTPS
# siempre, durante este tiempo". Evita el primer salto por HTTP, que es
# donde se puede interceptar la conexion.
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
# ============================================================
# Django REST Framework
# ============================================================
REST_FRAMEWORK = {
    # JWT como mecanismo de autenticación por defecto.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Permiso por defecto: público. Cada vista decide si requiere
    # autenticación (con IsAuthenticated) o no (con AllowAny).
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


# ============================================================
# JWT (djangorestframework-simplejwt)
# ============================================================
SIMPLE_JWT = {
    # El access token caduca a los 60 minutos. Pasado ese tiempo, el
    # cliente debe usar el refresh token para pedir uno nuevo.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    # El refresh token caduca a los 7 días. Si caduca, el usuario
    # tendrá que volver a hacer login.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # No rotamos los refresh tokens (al refrescar, el refresh sigue
    # siendo el mismo). Más simple para esta primera implementación.
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,

    # Cabecera HTTP estándar: Authorization: Bearer <token>
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Aviso silenciado a proposito:
# security.W021 pide activar SECURE_HSTS_PRELOAD para entrar en la lista
# de precarga de los navegadores. No lo activamos: salir de esa lista
# lleva meses y ataria el dominio. Se revisara si algun dia interesa.
SILENCED_SYSTEM_CHECKS = ['security.W021']
