# Generated by Django 5.0.6 on 2026-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='intervalo_entrega',
            field=models.CharField(blank=True, choices=[('09-12', '09:00 - 12:00'), ('12-15', '12:00 - 15:00'), ('15-18', '15:00 - 18:00'), ('18-21', '18:00 - 21:00')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('bizum', 'Bizum'), ('transferencia', 'Transferencia')], default='tarjeta', max_length=20),
        ),
    ]
