# Generated by Django 5.0.6 on 2026-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_ciudad_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('pagomovil', 'Pago Movil'), ('transferencia', 'Transferencia')], default='tarjeta', max_length=20),
        ),
    ]
