# Generated by Django 5.0.6 on 2026-05-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('descripcion', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel (0 = primero)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
