# Generated by Django 5.0.6 on 2026-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades_por_pack',
            field=models.PositiveIntegerField(default=1, help_text='Unidades incluidas en el precio (ej. 3 para "× 3 und.").'),
        ),
    ]
